### PR TITLE
containers: add fedora-37/38 and remove fedora-35 containers

### PR DESCRIPTION
**Pull request by aesteve-rh**
Fixes: https://github.com/oVirt/ovirt-imageio/issues/159
Signed-off-by: Albert Esteve <aesteve@redhat.com>

### CODE REVIEW

**Review by nirs — APPROVED** [review]

**Comment by nirs** [comment]
@aesteve-rh awesome!

**Comment by aesteve-rh** [comment]
@ahadas could you please remove the fedora-35 jobs from being required in the project settings? And probably adding the new ones too (`CI / test (fedora-37, py311)` and `CI / test (fedora-38, py311)`).

Thanks!

**Review by ahadas — APPROVED** [review]
removed fedora-35 and added 37 and 38

**Comment by aesteve-rh** [comment]
@ahadas thanks!

**Pull request merged**
