### PR TITLE
Build container add python3.11 to el8 

### PR DESCRIPTION
**Pull request by mnecas**

### CODE REVIEW

**Comment by mnecas** [comment]
There should be no change. We already require python3.11

**Review by aesteve-rh — APPROVED** [review]
lgtm

**Comment by aesteve-rh** [comment]
Uhm, it failed with `No match for argument: python3.11-pip`

https://github.com/oVirt/ovirt-imageio/actions/runs/4508906117/jobs/7938056619#step:4:180

**Comment by mnecas** [comment]
Hmm do we even need the pip?

**Comment by aesteve-rh** [comment]
I'll try to build without it.

Related to the missing `python3.11-pip` -> https://issues.redhat.com/browse/CS-1502

**Pull request merged**
