### PR TITLE
Reorder python builds

### PR DESCRIPTION
**Pull request by nirs**
Based on #186:
- Squash fix commits to one commit
- Add missing signed-off-by

### CODE REVIEW

**Comment by nirs** [comment]
EPEL9* builds still fail with this change but the rest of the builds are fine.
https://copr.fedorainfracloud.org/coprs/nsoffer/ovirt-imageio-preview/build/5602633/

**Comment by mwperina** [comment]
EPEL9 builds are failing because python 3.11 is not yet there:
```
No matching package to install: 'python3.11-devel'
No matching package to install: 'python3.11-setuptools'
```
So this will probably be fixed only when RHEL 9.2 is released, right?

**Review by michalskrivanek — APPROVED** [review]

**Review by aesteve-rh — APPROVED** [review]
I'll make a new release then.

**Comment by michalskrivanek** [comment]
releases are fine (CBS builds), this basically just fixes COPR/nightly

**Comment by aesteve-rh** [comment]
Great, thanks @michalskrivanek for the fix and @nirs for putting it together :)

**Pull request merged**
