### PR TITLE
CODEOWNERS: Add oVirt documentation team

### PR DESCRIPTION
**Pull request by nirs**
Add @oVirt/ovirt-documentation to watch the docs/ and README.md.

### CODE REVIEW

**Comment by stoobie** [comment]
@nirs By adding the ovirt documentation team to the ovirt-imageio repo, what is the expectation from the docs team?

**Review by emarcusRH — APPROVED** [review]

**Comment by emarcusRH** [comment]
> 

I discussed this with Nir - to be able to have someone in Docs proof read changes - primarily to the Readme document, but occasionally to other docs in the VDSM development repo. I am willing to take this upon myself, but in case I am not available - it is tagged by default to the ovirt/docs

**Comment by nirs** [comment]
> @nirs By adding the ovirt documentation team to the ovirt-imageio repo, what is the expectation from the docs team?

My expectation is to get a review for changes if the doc team have time for this.

I hope that this will improve the quality of user visible parts like the README
and developer documentation.

**Comment by stoobie** [comment]
> > @nirs By adding the ovirt documentation team to the ovirt-imageio repo, what is the expectation from the docs team?
> 
> My expectation is to get a review for changes if the doc team have time for this.
> 
> I hope that this will improve the quality of user visible parts like the README and developer documentation.

OK, as long as it's clear that this would be a best-effort situation.

**Review by vjuranek — APPROVED** [review]

**Pull request merged**
